spring:
  application:
    name: sicier
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    jwt:
      private:
        key: ${JWT_PRIVATE_KEY}
    user:
      generator: ${JWT_USER_GENERATOR:sicierDev}
