spring:
  application:
    name: sicier
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: create-drop