spring:
  application:
    name: sicier
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  flyway:
    password: ${DATASOURCE_PASSWORD}
  security:
    jwt:
      private:
        key: ${JWT_PRIVATE_KEY}
    user:
      generator: ${JWT_USER_GENERATOR:sicierDev}
