spring:
  application:
    name: sicier
  flyway:
    enabled: false
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/sicier-dev
  jpa:
    hibernate:
      ddl-auto: create