spring:
  application:
    name: sicier
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    jwt:
      private:
        key: ${JWT_PRIVATE_KEY}
    user:
      generator: ${JWT_USER_GENERATOR:sicierDev